apiVersion: v2
name: datahub
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: datahub
    repository: https://helm.datahubproject.io/
    version: 0.3.12
