import * as pulumi from "@pulumi/pulumi";
import * as snowflake from "@pulumi/snowflake";
import * as random from "@pulumi/random";
import * as k8s from "@pulumi/kubernetes";
import { OpenMetadataSnowflake } from "./snowflake";

const CHARTS_PATH = "./charts";

interface DatahubK8sArgs {
  namespace: string;
  snowflake: OpenMetadataSnowflake;
}

export class OpenmetadataK8s extends pulumi.ComponentResource {
  namespace: k8s.core.v1.Namespace;
  chart: k8s.helm.v3.Chart;

  constructor(
    name: string,
    args: DatahubK8sArgs,
    opts?: pulumi.ComponentResourceOptions
  ) {
    super("pkg:index:OpenMetadataK8s", name, opts);

    // Kubernetes Resources
    this.namespace = new k8s.core.v1.Namespace(
      "namespace",
      {
        metadata: {
          name: args.namespace,
        },
      },
      { parent: this }
    );

    const mysqlPassword = new random.RandomPassword("mysql", { length: 16 });
    const mysqlSecret = new k8s.core.v1.Secret(
      "mysql",
      {
        type: "Opaque",
        metadata: {
          name: "mysql-secrets",
          namespace: this.namespace.metadata.name,
        },
        stringData: {
          "openmetadata-mysql-password": mysqlPassword.result,
        },
      },
      { parent: this }
    );

    const airflowPassword = new random.RandomPassword("airflow", {
      length: 16,
    });
    const airflowSecret = new k8s.core.v1.Secret(
      "airflow",
      {
        type: "Opaque",
        metadata: {
          name: "airflow-secrets",
          namespace: this.namespace.metadata.name,
        },
        stringData: {
          "openmetadata-airflow-password": airflowPassword.result,
        },
      },
      { parent: this }
    );

    const airflowMysqlPassword = new random.RandomPassword("airflow-mysql", {
      length: 16,
    });
    const airflowMysqlSecret = new k8s.core.v1.Secret(
      "airflow-mysql",
      {
        type: "Opaque",
        metadata: {
          name: "airflow-mysql-secrets",
          namespace: this.namespace.metadata.name,
        },
        stringData: {
          "openmetadata-airflow-mysql-password": airflowMysqlPassword.result,
        },
      },
      { parent: this }
    );

    new k8s.core.v1.Secret(
      "snowflake",
      {
        type: "Opaque",
        metadata: {
          name: "snowflake",
          namespace: this.namespace.metadata.name,
        },
        stringData: {
          account: snowflake.config.account!,
          username: args.snowflake.user.name,
          password: args.snowflake.user.password.apply((v) => v!),
          warehouse: args.snowflake.warehouse.name,
          role: args.snowflake.role.name,
        },
      },
      { parent: this }
    );

    this.chart = new k8s.helm.v3.Chart(
      "datahub",
      {
        namespace: this.namespace.metadata.name,
        path: CHARTS_PATH,
        chart: "openmetadata",
      },
      {
        parent: this,
        // Pulumi keeps trying to force replace the secrets generated by the helm chart due to new credentials being generated on plan.
        // ignoring data inside the secrets will stop this, also has no effect on outside parameters
        // https://www.pulumi.com/docs/concepts/options/transformations/
        // transformations: [
        //   (args) =>
        //     args.type == "kubernetes:core/v1:Secret"
        //       ? {
        //           props: args.props,
        //           opts: pulumi.mergeOptions(args.opts, {
        //             ignoreChanges: ["data"],
        //           }),
        //         }
        //       : undefined,
        // ]
      }
    );

    this.registerOutputs({
      chart: this.chart,
    });
  }
}
